### ISSUE TITLE
"UNHANDLED PACKET type: V" while transmitting from Xastir

### ISSUE THREAD

**Issue by jpalczewski** [alejolp/extmodem#11]
Hi,

I'm working on a APRS-related project on Raspberry Pi powered by Archlinux ARM - extmodem is much more better at decoding real APRS packets recorded from radio than soundmodem while using cheap, chinese USB cards, but I have other kind of problems: 

After running Xastir, logs from debug instance, executed in this way:
`/usr/bin/extmodem --audio-backend alsa --agwpe-tcp-port 8000 --kiss-tcp-port 6666 --ptt-mode null -s 48000 --in-chan 1 --t-chan 2 --debug --alsa-device "plughw:0,0" `

Results in:
```
AGWPE New TCP connection, 1 total.
AGWPE new data 108
AGWPE new frame kind: R
AGWPE new frame kind: G
AGWPE new frame kind: k
AGWPE new data 92
AGWPE new frame kind: V
AGWPE UNHANDLED PACKET type: V
```
I configured Xastir to use AGWPE without success - every time I click "Transmit now!" or trying to send any message, I receive that error in log.

Have you discovered any successful way to connect extmodem to Xastir?

If it might be useful -  `aplay -L` output:
```
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=Device
    USB PnP Audio Device, USB Audio
    Default Audio Device
sysdefault:CARD=Device
    USB PnP Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB PnP Audio Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
```

**Comment by alejolp** [comment]
Hi! You should upgrade your extmodem version. V frames support for xastir was added less than a month ago.

**Comment by jpalczewski** [comment]
That's true, today compiled version works with Xastir and it is possible to decode frames even from webSDRs. Thanks for help and maintaining such a great project!
