### ISSUE TITLE
Compiler error. 

### ISSUE THREAD

**Issue by mvdswaluw** [alejolp/extmodem#7]
Had problems compiling on Rpi2.

In build.py -> CFLAGS -> "-std=c++11" should be "-std=c++0x".

**Comment by alejolp** [comment]
Thanks! I'm about to get into a 24hs plane trip. Wanna make a pull request? 
We should also migrate to a better build system, ie CMake. You can copy-past [other CMakeLists.txt file from other project](https://github.com/DakaraOnline/dakara-server/blob/master/CMakeLists.txt).
Thanks

**Comment by mvdswaluw** [comment]
After that I had more errors. Found out "-lasound" and "-lpthread" should be added to LDFLAGS.

**Comment by mvdswaluw** [comment]
Done. Thanks.

**Comment by alejolp** [comment]
Merged
